 FROM nginx

  RUN apt-get update -qq && apt-get -y install apache2-utils
  ENV NODE_ROOT /var/www/api-gateway
  WORKDIR $NODE_ROOT
  RUN mkdir log
  COPY app.conf /tmp/app.nginx
  RUN envsubst '$NODE_ROOT' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf
  
  # Variable de entorno para el host de la interfaz
#   ENV API_INTERFACE_HOST sae_int:3037
  ENV API_INTERFACE_HOST sae-int-service.p5.svc.dns-private:3037
  WORKDIR $API_INTERFACE_HOST
  RUN mkdir log
  COPY app.conf /tmp/app.nginx
  RUN envsubst '$API_INTERFACE_HOST' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf

  EXPOSE 80

  CMD [ "nginx", "-g", "daemon off;" ]
