 FROM nginx

  RUN apt-get update -qq && apt-get -y install apache2-utils
  ENV NODE_ROOT /var/www/api-gateway
  WORKDIR $NODE_ROOT
  RUN mkdir log
  COPY app.conf /tmp/app.nginx
  RUN envsubst '$NODE_ROOT' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf
  
  # Variable de entorno para el host del web app
  ENV API_WEB_HOST sae_ag:80
  RUN envsubst '$API_WEB_HOST' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf

  #
  COPY key.pem /etc/ssl/private/key.pem
  COPY server.crt /etc/ssl/certs/server.crt

  EXPOSE 433

  CMD [ "nginx", "-g", "daemon off;" ]
