 FROM nginx

  RUN apt-get update -qq && apt-get -y install apache2-utils
  ENV NODE_ROOT /var/www/api-gateway
  WORKDIR $NODE_ROOT
  RUN mkdir log
  COPY app.conf /tmp/app.nginx
  RUN envsubst '$NODE_ROOT' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf

# Variable de entorno para el host del api gateway
  # ENV API_GATEWAY_HOST sae_ag:80
  ENV API_GATEWAY_HOST sae-ag-service.p5.svc.dns-private.:3121
  WORKDIR $API_GATEWAY_HOST
  RUN mkdir log
  COPY app.conf /tmp/app.nginx
  RUN envsubst '$API_GATEWAY_HOST' < /tmp/app.nginx > /etc/nginx/conf.d/default.conf

  EXPOSE 80

  CMD [ "nginx", "-g", "daemon off;" ]